language: node_js
node_js:
  - '10.16.2'
env:
  - MONGO_URI="test"
addons:
  apt:
    packages:
      - xvfb
install:
  - npm i
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &