language: node_js
node_js:
  - '10.16.2'
env:
  - secure: "OuJr67M7r+SSxq6wWUqkFZPbmcvvPuwuAXLTnjG+VyqRrPFkc3UcY4Ougxlc3t/YbeE8sgPXTXL61JccTHcgMGowrLSIdnlYzN6r922cg7KReVRbxnHaw1z4M/mlK9/haXjfuTIL/iwMrbnaJCLWdwD4rW3BxzCQMGhcWWgDQhB+2VO3kzNBjUN5ab8nxUWDzE/vhuZAaxu4kE1xoV6LNChduSHMfyt+pNMOk6Z2pcyyw1WeXF5pnDwKcrznmFxSjd6SC1MbC73XNUvjb4d/5EY8lgMCiRRVfeiRTYfd3ODwCyoqFCQkVjGCLGdC9tVls4h5VrWG75d6wEjaY0his5D2T/7gOhqszLW8+nOxxo+hYeFToV4fln7uui6gna75O4MabhoDsB9wKS9YUGyss9l4v/ybYRN6X7cOxEav6n77OcBedHGtZcPXmhgcT3lcI7mjnKSGKThd/p3IYx4I0JSXXvo88O+tMQipBkii5scUfvBxllBSzjRsyhia13xZCxBt00V9jDq3ibz+wV4uPPu1wISFg+sfSeIQzj16FxMWHFV763UUncQWL+R2EMCt25B3eH7VG4VjklIwEGCdv7m4HICugsdfAhkqReY1mSVUD3AKL2YPdKtGuYI67RhzAB95DbRe1kdXaURh43saKg4uSy1msYEG4X4l10kb2t4="
addons:
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &