language: node_js
node_js:
  - '10.16.2'
env:
  global:
    secure: "EcDpglneKlcUk46Pu0v7722NOe2k6jwfews7Nf9lbkG7aQG7fyU6pyt2210J1HKRBrzZODd4kl8pJhYnIDPoDfIZUulokVbCVahY16Y906lKJD/1YtX34iG8/Uwako3zbnVsSfnDPiWnPhjCCPhipKVeuxr/FZl60BgdqcG+kOwMIY0uMg4XGuOibUQnVswstrvYDFKSh8W0Wo8JPatIIb+Ox/Pjs7aBDM7LVv8VkUzxjT+ID9L9WK7mpD2a+kHUesNwQcJp4CqUg5a/JhnfGQcoopxvNjHVQLODCNTHaplcWK4PKG6vlatmh3CwGVojgXnCvAJq0mTznU30AUgI46zbKqLv+Mh22mT269ON1qRbZ59+9MK097ZqIrFk+jWU7S/Z/OICOwzF5O59uzCFpm5OWdk7RqeitG1m1vqT1JS9cQfcEI8FCkAb739MhNT/lEeYihOYcg6+sGx12b3hq1hLQjidkBH+SYhm//7yl3VwiAT1mjeXbfCRcDLdErBNzobjHwu7vGkW12GQQLgYBB1OFDWpmUeTWX76hbKGVCFYFBlLTB4ewCek6t9a8SRQauc501kQcMiYRDZ637IZf71iN1RE3BrVDF6x0iL2e+lx0pNJK30ueCKtztIIZ0knLgW7ZUY/r7EugBEPhDytRIaMHmCAXHLx/A5S3/BPquQ="
addons:
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &